deps script cleanup

diff --git a/bin/deps b/bin/deps
--- a/bin/deps
+++ b/bin/deps
@@ -4,17 +4,6 @@
 # second column into the first column. A poor man's package manager if
 # you will...
 
-echo $TTY
-
-printline() {
-	if [ -t 1 ]; then
-		printf "\e[1A"
-		printf "\e[0K\r%s\n" "$1"
-	else
-		echo "$1"
-	fi
-}
-
 if [ ! -f dependencies.tsv ]; then
 	>&2 echo "No 'dependencies.tsv' file"
 	exit 1
@@ -29,6 +18,29 @@ if [ ! -d $DEST ]; then
 	printf "%s\n\n" "Creating $DEST..."
 	mkdir -p $DEST
 fi
+
+printline() {
+	if [ -t 1 ]; then
+		printf "\e[1A"
+		printf "\e[0K\r%s\n" "$1"
+	else
+		echo "$1"
+	fi
+}
+
+fetch() {
+	if curl --disable \
+			--location \
+			--silent \
+			--fail-with-body \
+			--output "$DEST/$1" \
+			"$2"; then
+		printline "$1"
+	else
+		printf "%s\n\n" "FAILED to fetch $1!"
+		exit 1
+	fi
+}
 
 while read -r line
 do
@@ -47,11 +59,7 @@ EOF
 		continue
 	fi
 
-	if curl --location --silent --fail-with-body --output "$DEST/$target" "$origin"; then
-		printline "$target"
-	else
-		printf "%s\n\n" "FAILED to fetch $target!"
-	fi
+	fetch "$target" "$origin"
 done <dependencies.tsv
 
 printline "deps finished"
